export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLE_REQUEST'
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLE_FAILURE'

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS'
export const CREATE_COMMENTS_FAILURE = 'CREATE_COMMENTS_FAILURE'
export const CREATE_COMMENTS_REQUEST = 'CREATE_COMMENTS_REQUEST'

export const SET_PAGE_REQUEST = 'SET_PAGE_REQUEST'
export const SET_PAGE_SUCCESS = 'SET_PAGE_SUCCESS'

export const SEARCH_ARTICLES = 'SEARCH_ARTICLES'


